apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecostream-visualizer-ingress
  namespace: "{{ .Values.namespace }}"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    # - host: "ecostream-visualizer.local" # change to custom host name when Route 53 is configured (?)
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.components.ecostreamVisualizer.serviceName }}"
                port:
                  number: {{ .Values.components.ecostreamVisualizer.port }}
