apiVersion: batch/v1
kind: Job
metadata:
  name: ecostream-import-data
  namespace: "{{ .Values.namespace }}"
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      serviceAccountName: ecostream-sa
      containers:
        - name: import-data
          image: "{{ .Values.tools.kubectl.image.repository }}:{{ .Values.tools.kubectl.image.tag }}"
          env:
          - name: ECOSTREAM_MANAGER_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.settings.ecostreamConfiMapName }}
                key: ECOSTREAM_MANAGER_URL
          - name: ECOSTREAM_MANAGER_USERNAME
            valueFrom:
              secretKeyRef:
                name: ecostream-manager-secret
                key: ECOSTREAM_MANAGER_USERNAME
          - name: ECOSTREAM_MANAGER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ecostream-manager-secret
                key: ECOSTREAM_MANAGER_PASSWORD
          - name: import-data.sh
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.settings.ecostreamConfiMapName }}
                key: import-data.sh
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e

              echo "Extracting GitLab credentials from secret"
              gitlabRegistryCreds=$(cat /dockerconfig/.dockerconfigjson | base64 -d | jq -r '.auths["https://registry.gitlab.com"]')
              gitlabUser=$(echo $CREDS | jq -r '.username')
              gitlabPassword=$(echo $CREDS | jq -r '.password')
              echo "Cloning GitLab database repository"
              git clone https://${gitlabUser}:${gitlabPassword}@gitlab.com/gkermo/ecostream-database.git
              cd ecostream-database/data
              ./populate_ecostream_db.sh

              echo "Done!"
          volumeMounts:
            - name: docker-secret
              mountPath: /dockerconfig
              readOnly: true
      volumes:
        - name: docker-secret
          secret:
            secretName: ecostream-container-registry-secret
      restartPolicy: Never
  backoffLimit: 2
