apiVersion: batch/v1
kind: Job
metadata:
  name: ecostream-import-data
  namespace: "{{ .Values.namespace }}"
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      serviceAccountName: ecostream-sa
      containers:
        - name: import-data
          image: "{{ .Values.tools.alpine.image.repository }}:{{ .Values.tools.alpine.image.tag }}"
          env:
          - name: ECOSTREAM_MANAGER_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.settings.ecostreamConfiMapName }}
                key: ECOSTREAM_MANAGER_URL
          - name: ECOSTREAM_MANAGER_USERNAME
            valueFrom:
              secretKeyRef:
                name: ecostream-manager-secret
                key: ECOSTREAM_MANAGER_USERNAME
          - name: ECOSTREAM_MANAGER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ecostream-manager-secret
                key: ECOSTREAM_MANAGER_PASSWORD
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e

              echo "Extracting GitLab credentials from secret..."
              gitlabRegistryCreds=$(cat /dockerconfig/.dockerconfigjson | jq -r '.auths["https://registry.gitlab.com"]')
              gitlabUser=$(echo $gitlabRegistryCreds | jq -r '.username')
              gitlabPassword=$(echo $gitlabRegistryCreds | jq -r '.password')
              echo "Cloning GitLab database repository"
              cd /tmp
              git clone https://${gitlabUser}:${gitlabPassword}@gitlab.com/gkermo/ecostream-database.git
              cd ecostream-database/data
              echo "Running populate database script..."
              ( . populate_ecostream_db.sh )
              exit_code=$?
              if [[ $exit_code -ne 0 ]]; then
                  echo "Populate database script failed, there might already be some data" >&2
              else
                  echo "Populate database script completed successfully"
              fi

              echo "Done!"
              exit 0

          volumeMounts:
            - name: docker-secret
              mountPath: /dockerconfig
              readOnly: true
            - name: cache-volume
              mountPath: /tmp
      volumes:
        - name: docker-secret
          secret:
            secretName: ecostream-container-registry-secret
        - name: cache-volume
          emptyDir: {}
      restartPolicy: Never
  backoffLimit: 2
