apiVersion: batch/v1
kind: Job
metadata:
  name: ecostream-post-deploy
  namespace: "{{ .Values.namespace }}"
spec:
  template:
    spec:
      serviceAccountName: ecostream-sa
      containers:
      - name: post-deploy-configuration
        image: "{{ .Values.tools.kubectl.image.repository }}:{{ .Values.tools.kubectl.image.tag }}"
        env:
        - name: NAMESPACE
          value: "{{ .Values.namespace }}"
        command: [ "/bin/sh", "-c" ]
        args:
        - |
          set -e
          
          echo "Does not do anything for now..."

          echo "Done!"

      restartPolicy: Never
  backoffLimit: 2
