apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecostream-manager-ingress
  namespace: "{{ .Values.namespace }}"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "ecostream-manager.local" # 192.168.49.2 # minikube ip, this should be set to the EKS host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.components.ecostreamManager.serviceName }}"
                port:
                  number: {{ .Values.components.ecostreamManager.port }}
