apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ecostream-database
  namespace: "{{ .Values.namespace }}"
  labels:
    app: ecostream-database
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: {{ .Values.settings.ha | ternary 3 1 }}
  selector:
    matchLabels:
      app: ecostream-database
  template:
    metadata:
      labels:
        app: ecostream-database
    spec:
      imagePullSecrets:
        - name: ecostream-container-registry-secret
      containers:
      - name: postgres
        image: "{{ .Values.components.ecostreamDatabase.image.repository }}:{{ .Values.components.ecostreamDatabase.image.tag }}"
        imagePullPolicy: Always
        # debug
        # command: ["/bin/sh", "-c"]
        # args:
        #   - |
        #     while true; do
        #       sleep 3600
        #     done
        ports:
        - containerPort: {{ .Values.components.ecostreamDatabase.port }}
          name: db-http
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: ecostream-database-secret
                key: ECOSTREAM_DB_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ecostream-database-secret
                key: ECOSTREAM_DB_PASSWORD
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: ecostream-volume
  volumeClaimTemplates:
    - metadata:
        name: ecostream-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp2
        resources:
          requests:
            storage: 1Gi
