apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecostream-pvc
  namespace: "{{ .Values.namespace }}"
  labels:
    type: local
    app: ecostream-database
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
