namespace: ecostream
components:
  ecostreamManager:
    serviceName: ecostream-manager-service
    port: 9000
    image:
      repository: registry.gitlab.com/gkermo/ecostream-manager
      tag: main-cfb453a5-amd64
  ecostreamVisualizer:
    serviceName: ecostream-visualizer-service
    port: 80
    image:
      repository: registry.gitlab.com/gkermo/ecostream-visualizer
      tag: main-7fb08b80-amd64
  ecostreamDatabase:
    serviceName: ecostream-database-service
    port: 5432
    image:
      repository: registry.gitlab.com/gkermo/ecostream-database
      tag: main-7cc55721-amd64
settings:
  ha: false
  ecostreamConfiMapName: "ecostream-configmap"
  # commenting for now. It's workinb but it takes a few minutes or even hours for DNS propagation to be properly done
  # for a dev env, it would be better to use an nginx ingress controller and self-signed certificates or some other handy solution for dev
  ecostreamHostname: "kermo.click"
  # ARN of certificate in AWS Certificate Manager (ACM)
  certificateARN: "arn:aws:acm:eu-west-3:531920760589:certificate/f1f058cf-9e44-4fc4-bada-048e7a4abf2e"
tools:
  kubectl:
    image:
      repository: registry.gitlab.com/gkermo/ecostream/base_images/bitnami-kubectl
      tag: 1.32-amd64
  alpine:
    image:
      repository: registry.gitlab.com/gkermo/ecostream/base_images/alpine
      tag: 3.19-amd64
