apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.components.ecostreamManager.serviceName }}"
  namespace: "{{ .Values.namespace }}"
spec:
  selector:
    app: ecostream-manager
  ports:
    - port: {{ .Values.components.ecostreamManager.port }}
      targetPort: manager-http
  type: ClusterIP