apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecostream-manager-ingress
  namespace: "{{ .Values.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
{{- if .Values.settings.certificateARN }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.settings.certificateARN }}"
{{- else  }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
{{ end }}
{{- if .Values.settings.ecostreamHostname }}
    external-dns.alpha.kubernetes.io/hostname: "manager.{{ .Values.settings.ecostreamHostname }}"
{{- end  }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.components.ecostreamManager.serviceName }}"
                port:
                  number: {{ .Values.components.ecostreamManager.port }}
{{- if .Values.settings.ecostreamHostname }}
      host: "manager.{{ .Values.settings.ecostreamHostname }}"
{{- end  }}