apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecostream-sa
  namespace: "{{ .Values.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
imagePullSecrets:
  - name: ecostream-container-registry-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecostream-role
  namespace: "{{ .Values.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "update", "patch", "get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecostream-role-binding
  namespace: "{{ .Values.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: ecostream-sa
    namespace: "{{ .Values.namespace }}"
roleRef:
  kind: Role
  name: ecostream-role
  apiGroup: rbac.authorization.k8s.io
