# Must be deployed as a prereq from configuration script
apiVersion: v1
data:
  ECOSTREAM_MANAGER_PASSWORD: bWFuYWdlci1wYXNzd29yZA==
  ECOSTREAM_MANAGER_USERNAME: bWFuYWdlcg==
kind: Secret
metadata:
  name: ecostream-manager-secret
  namespace: "{{ .Values.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: v1
data:
  ECOSTREAM_DB_USER: ZWNvc3RyZWFtLWRiLXVzZXI=
  ECOSTREAM_DB_PASSWORD: ZWNvc3RyZWFtLWRiLXBhc3N3b3Jk
kind: Secret
metadata:
  name: ecostream-database-secret
  namespace: "{{ .Values.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "1"